name: bodykitmaster
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  sidebarx: ^0.17.1
  geolocator: ^13.0.1
  flutter_osm_plugin: ^1.0.5
  flutter_hooks: ^0.20.5
  pointer_interceptor: ^0.10.1+1
  popup_menu: ^2.0.0
  two_dimensional_scrollables: ^0.3.0
  table_calendar: ^3.0.1
  intl: ^0.17.0
  charts_flutter: ^0.12.0

  flutter_map: ^7.0.1
  flutter_ringtone_player: ^4.0.0+3

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  latlong2: ^0.9.1

  url_launcher: ^6.1.8
  uuid: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

